name: PyBack-Linkedevents CI

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - '**'

jobs:
  build_job:
    runs-on: ubuntu-18.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        include:
          - arch: aarch64
            distro: ubuntu18.04

    services:
      postgres:
        image: postgis/postgis:11-2.5
        env:
          POSTGRES_USER: linkedevents
          POSTGRES_PASSWORD: linkedevents
          POSTGRES_DB: linkedevents
          DEBUG: true
          SECRET_KEY: linkedevents_secret
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          python-version: ${{ matrix.python-version }}

      - name: Update & Upgrade Linux
        run: |
          sudo apt-get update
          sudo apt-get upgrade

      - name: Install Libraries
        run: |
           sudo apt-get install nginx virtualenv python3-virtualenv python3-dev python3-pip build-essential libpq-dev -y
      
      - name: Assign FIN Locale
        run: |
          sudo locale-gen fi_FI.UTF-8
          
      - name: Create DB & Extensions
        run: |
          sudo -u postgres createdb -O linkedevents -T template0 -l fi_FI.UTF-8 linkedevents
          sudo -u postgres psql linkedevents -c "CREATE EXTENSION postgis;"
          sudo -u postgres psql linkedevents -c "CREATE EXTENSION hstore;"
      
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Apply migrations
        env:
          DATABASE_URL: postgis://linkedevents:linkedevents@localhost/linkedevents
          DEBUG: true
          SECRET_KEY: linkedevents_secret
        run: |
          python3 manage.py migrate
          
      - name: Sync translations
        env:
          DATABASE_URL: postgis://linkedevents:linkedevents@localhost/linkedevents
          DEBUG: true
          SECRET_KEY: linkedevents_secret
        run: |
          python3 manage.py sync_translation_fields
       

      - name: Run tests
        env:
          DATABASE_URL: postgis://linkedevents:linkedevents@localhost/linkedevents
          DEBUG: true
          SECRET_KEY: linkedevents_secret
        run: |
          pytest --cov . --doctest-modules
